name: Stable Branch Sync

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
    types: 
        - closed

jobs:
  get-next-version:
    runs-on: ubuntu-latest
    outputs:
      next-version: ${{ env.NEXT_SEMVER_VERSION }}
    steps:
        - name: Get the next semver version
          id: get-next-semver-version
          env:
            FORCE_NEXT_SEMVER_VERSION: ${{ vars.FORCE_NEXT_SEMVER_VERSION }}
          run: ./get-next-semver-version.sh "$FORCE_NEXT_SEMVER_VERSION"
          working-directory: '.github/scripts'

  run-stable-sync:
    needs: get-next-version
    uses: metamask/github-tools/.github/workflows/stable-sync.yml@ale/infra-2532-master-sync-pr
    with:
      semver-version: ${{ needs.get-next-version.outputs.next-version }}

